export TERM="xterm-256color"

shopt -s checkwinsize
shopt -s expand_aliases

# Enable history appending instead of overwriting.  #139609
shopt -s histappend

#
# General Aliases
#

alias ls='ls --color=yes'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

#
# Git Aliases
#

alias gs="git status"
alias gd="git diff"
alias gc="git commit"
alias gl="git log --oneline --pretty --graph"

#
# Custom Tools
#

add_path() {
  export PATH="$1":$PATH
}

THIRD=${HOME}/third_party
export PATH=${THIRD}:$PATH

#
# Custom Prompt
#

generate_prompt() {
  export PS1=$(${HOME}/nova/prompt/build/deployed $?)
}
PROMPT_COMMAND=generate_prompt

#
# Other Utils
#

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/myles/third_party/conda/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/myles/third_party/conda/etc/profile.d/conda.sh" ]; then
        . "/home/myles/third_party/conda/etc/profile.d/conda.sh"
    else
        export PATH="/home/myles/third_party/conda/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

