export TERM="xterm-256color"

#
# General Aliases
#

alias ls='ls --color=yes'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

#
# Git Aliases
#

alias gs="git status"
alias gd="git diff"
alias gc="git commit"
alias gl="git log --oneline --pretty --graph"

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

#
# Python Environment
#

export PATH=${HOME}/.pyenv/bin:${PATH}
