"
"   plugins with vim-plug
"

call plug#begin('~/.vim/plugged')

Plug 'tpope/vim-sensible'
Plug 'tpope/vim-fugitive'
Plug 'christoomey/vim-tmux-navigator'
Plug 'benmills/vimux'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'dracula/vim', { 'as': 'dracula' }
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
Plug 'romainl/Apprentice'
Plug 'Valloric/YouCompleteMe'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

call plug#end()

"
"   basic settings
"

set t_Co=256
syntax on
set number
set ts=2
set shiftwidth=2
set expandtab
set autoindent
set smartindent
set noswapfile
set nobackup
set showmatch
set hlsearch
set incsearch
set mouse=c
set title
set laststatus=2
set backspace=indent,eol,start
set lazyredraw

"
"   colorscheme
"

colorscheme apprentice
let g:airline_theme='tomorrow'

"
"   filetype behavior
"

filetype plugin indent on

au BufRead,BufNewFile *.sv set filetype=verilog
au BufRead,BufNewFile *.svh set filetype=verilog
au BufRead,BufNewFile *.vh set filetype=verilog
au! FileType python setl nosmartindent
au! FileType verilog setl nosmartindent
au! FileType sass setl sw=2

"
"   vimux
"

map <leader>rx :VimuxPromptCommand<CR>
map <leader>rr :VimuxRunLastCommand<CR>

"
"   you complete me
"

set completeopt-=preview
