#!/bin/bash

sudo apt-get install -y \
git \
vim \
tmux \
build-essential \
python3 \
python-numpy \
chromium-browser \
curl \
net-tools \
feh \
neofetch \

# vim-plugged installer
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
